{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "66cba7c0-bde4-4708-b01c-788a48bec927",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Data loaded\n",
      "   CO₂ 2023: 1.0 MtCO₂ | Per capita: 7.94 t | Change: -15.2%\n",
      "✅ Design tokens set\n",
      "✅ All charts built\n",
      "✅ UI helpers defined\n",
      "✅ Layout built\n",
      "✅ Callbacks registered\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x1db9a577bb0>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# ╔══════════════════════════════════════════════════════════════╗\n",
    "# ║         JAPAN CLIMATE DASHBOARD — JUPYTER NOTEBOOK          ║\n",
    "# ╚══════════════════════════════════════════════════════════════╝\n",
    "\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 1 — Install (run once)\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# !pip install dash dash-bootstrap-components plotly pandas openpyxl\n",
    "\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 2 — Imports\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "import pandas as pd\n",
    "import plotly.graph_objects as go\n",
    "from dash import Dash, html, dcc, Input, Output\n",
    "import dash_bootstrap_components as dbc\n",
    "\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 3 — Load & Prepare Data\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "FILE_PATH = \"Main data for Assignment.xlsx\"\n",
    "\n",
    "df_raw = pd.read_excel(FILE_PATH)\n",
    "df_raw.columns = [\n",
    "    'country', 'year', 'co2_total', 'co2_share', 'co2_per_capita',\n",
    "    'co2_consumption', 'gdp_per_capita', 'population',\n",
    "    'other_renewables', 'biofuels', 'solar', 'wind',\n",
    "    'hydropower', 'nuclear', 'gas', 'coal', 'oil'\n",
    "]\n",
    "df = df_raw[df_raw['year'] >= 1990].copy()\n",
    "japan = df[df['country'] == 'Japan'].reset_index(drop=True)\n",
    "india = df[df['country'] == 'India'].reset_index(drop=True)\n",
    "world = df[df['country'] == 'World'].reset_index(drop=True)\n",
    "\n",
    "japan['co2_mt']     = japan['co2_total'] / 1e9\n",
    "japan['renewables'] = japan['solar'] + japan['wind'] + japan['hydropower'] + japan['other_renewables']\n",
    "\n",
    "co2_2023      = japan[japan['year'] == 2023]['co2_mt'].values[0]\n",
    "pc_2023       = japan[japan['year'] == 2023]['co2_per_capita'].values[0]\n",
    "pc_2005       = japan[japan['year'] == 1990]['co2_per_capita'].values[0]\n",
    "pct_change    = round(((pc_2023 - pc_2005) / pc_2005) * 100, 1)\n",
    "share_2023    = japan[japan['year'] == 2023]['co2_share'].values[0]\n",
    "world_pc_2023 = world[world['year'] == 2023]['co2_per_capita'].values[0]\n",
    "india_pc_2023 = india[india['year'] == 2023]['co2_per_capita'].values[0]\n",
    "\n",
    "print(\"✅ Data loaded\")\n",
    "print(f\"   CO₂ 2023: {co2_2023:.1f} MtCO₂ | Per capita: {pc_2023:.2f} t | Change: {pct_change}%\")\n",
    "\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 4 — Design Tokens (Light Wabi-Sabi theme)\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "BG        = '#F7F7F5'\n",
    "CARD_BG   = '#FFFFFF'\n",
    "RED       = '#D9381E'\n",
    "BLUE      = '#1F456E'\n",
    "GREEN     = '#4A6B53'\n",
    "YELLOW    = '#B8860B'\n",
    "TEXT      = '#1A1A1A'\n",
    "SUBTEXT   = '#737373'\n",
    "BORDER    = '#E0E0DC'\n",
    "FONT_HEAD = 'Shippori Mincho, Georgia, serif'\n",
    "FONT_BODY = 'Inter, Helvetica Neue, sans-serif'\n",
    "\n",
    "PLOTLY_LAYOUT = dict(\n",
    "    paper_bgcolor='rgba(0,0,0,0)',\n",
    "    plot_bgcolor='rgba(0,0,0,0)',\n",
    "    font=dict(family=FONT_BODY, color=TEXT, size=12),\n",
    "    margin=dict(l=40, r=20, t=90, b=40),\n",
    "    legend=dict(bgcolor='rgba(0,0,0,0)', font=dict(color=SUBTEXT, size=11),\n",
    "                orientation='h', yanchor='bottom', y=1.02, xanchor='left', x=0),\n",
    "    xaxis=dict(showgrid=False, color=SUBTEXT, tickfont=dict(color=SUBTEXT),\n",
    "               linecolor=BORDER, zeroline=False),\n",
    "    yaxis=dict(showgrid=True, gridcolor=BORDER, color=SUBTEXT,\n",
    "               tickfont=dict(color=SUBTEXT), linecolor='rgba(0,0,0,0)', zeroline=False),\n",
    "    hoverlabel=dict(bgcolor=CARD_BG, bordercolor=BORDER,\n",
    "                    font=dict(family=FONT_BODY, color=TEXT))\n",
    ")\n",
    "\n",
    "ENERGY_COLORS = {\n",
    "    'coal':       ('#8B7355', 'rgba(139,115,85,0.75)'),\n",
    "    'oil':        ('#B8860B', 'rgba(184,134,11,0.75)'),\n",
    "    'gas':        ('#CD853F', 'rgba(205,133,63,0.75)'),\n",
    "    'nuclear':    ('#1F456E', 'rgba(31,69,110,0.75)'),\n",
    "    'renewables': ('#4A6B53', 'rgba(74,107,83,0.75)'),\n",
    "}\n",
    "ENERGY_LABELS = {'coal':'Coal','oil':'Oil','gas':'Gas','nuclear':'Nuclear','renewables':'Renewables'}\n",
    "\n",
    "print(\"✅ Design tokens set\")\n",
    "\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 5 — Static Charts (built once, callbacks will update some)\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "# Total CO2\n",
    "fig_total = go.Figure()\n",
    "fig_total.add_trace(go.Scatter(\n",
    "    x=japan['year'], y=japan['co2_mt'], mode='lines',\n",
    "    line=dict(color=RED, width=3), fill='tozeroy', fillcolor='rgba(217,56,30,0.08)',\n",
    "    hovertemplate='<b>%{x}</b><br>%{y:.1f} MtCO₂<extra></extra>'\n",
    "))\n",
    "for yr, lbl in [(2011,'Fukushima'),(2016,'Paris Agmt')]:\n",
    "    fig_total.add_vline(x=yr, line_dash='dash', line_color=SUBTEXT, line_width=1, opacity=0.5)\n",
    "    fig_total.add_annotation(x=yr, y=japan['co2_mt'].max(), text=lbl, showarrow=False,\n",
    "        font=dict(color=SUBTEXT, size=10, family=FONT_BODY), xshift=5, yshift=10)\n",
    "fig_total.update_layout(**PLOTLY_LAYOUT,\n",
    "    title=dict(text='Total CO₂ Emissions (MtCO₂)', font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "    yaxis_title='MtCO₂')\n",
    "\n",
    "# Per Capita\n",
    "fig_pc = go.Figure()\n",
    "fig_pc.add_trace(go.Scatter(\n",
    "    x=japan['year'], y=japan['co2_per_capita'], mode='lines',\n",
    "    line=dict(color=BLUE, width=3), fill='tozeroy', fillcolor='rgba(31,69,110,0.08)',\n",
    "    hovertemplate='<b>%{x}</b><br>%{y:.2f} tCO₂/person<extra></extra>'\n",
    "))\n",
    "for yr, lbl in [(2011,'Fukushima'),(2016,'Paris Agmt')]:\n",
    "    fig_pc.add_vline(x=yr, line_dash='dash', line_color=SUBTEXT, line_width=1, opacity=0.5)\n",
    "    fig_pc.add_annotation(x=yr, y=japan['co2_per_capita'].max(), text=lbl, showarrow=False,\n",
    "        font=dict(color=SUBTEXT, size=10, family=FONT_BODY), xshift=5, yshift=10)\n",
    "fig_pc.update_layout(**PLOTLY_LAYOUT,\n",
    "    title=dict(text='Per Capita CO₂ Emissions (tCO₂/person)', font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "    yaxis_title='tCO₂/person')\n",
    "\n",
    "# Comparison\n",
    "fig_compare = go.Figure()\n",
    "for entity, data, color, dash in [('Japan',japan,RED,'solid'),('India',india,GREEN,'dot'),('World',world,BLUE,'dash')]:\n",
    "    fig_compare.add_trace(go.Scatter(\n",
    "        x=data['year'], y=data['co2_per_capita'], mode='lines', name=entity,\n",
    "        line=dict(color=color, width=2.5, dash=dash),\n",
    "        hovertemplate=f'<b>{entity} %{{x}}</b><br>%{{y:.2f}} tCO₂/person<extra></extra>'\n",
    "    ))\n",
    "fig_compare.update_layout(**PLOTLY_LAYOUT,\n",
    "    title=dict(text='Per Capita CO₂: Japan vs India vs World', font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "    yaxis_title='tCO₂/person')\n",
    "\n",
    "# Donut\n",
    "japan_share = round(share_2023, 2)\n",
    "fig_donut = go.Figure(go.Pie(\n",
    "    labels=['Japan','Rest of World'], values=[japan_share, round(100-japan_share,2)],\n",
    "    hole=0.65, marker=dict(colors=[RED, BORDER]), textinfo='none',\n",
    "    hovertemplate='<b>%{label}</b><br>%{value:.2f}%<extra></extra>'\n",
    "))\n",
    "fig_donut.add_annotation(text=f'<b>{japan_share}%</b>', x=0.5, y=0.5, showarrow=False,\n",
    "    font=dict(color=TEXT, size=20, family=FONT_HEAD), align='center')\n",
    "fig_donut.update_layout(**PLOTLY_LAYOUT,\n",
    "    title=dict(text=\"Japan's Share of Global CO₂ (2023)\", font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "    showlegend=True)\n",
    "\n",
    "# Scatter\n",
    "fig_scatter = go.Figure()\n",
    "fig_scatter.add_trace(go.Scatter(\n",
    "    x=japan['gdp_per_capita'], y=japan['co2_per_capita'],\n",
    "    mode='markers+text', text=japan['year'].astype(str),\n",
    "    textposition='top center', textfont=dict(color=SUBTEXT, size=9),\n",
    "    marker=dict(size=10, color=japan['year'],\n",
    "        colorscale=[[0,'#E8D5C4'],[0.5,RED],[1,'#8B1A0A']], showscale=True,\n",
    "        colorbar=dict(title=dict(text='Year', font=dict(color=SUBTEXT)),\n",
    "                      tickfont=dict(color=SUBTEXT), outlinewidth=0)),\n",
    "    hovertemplate='<b>%{text}</b><br>GDP: $%{x:,.0f}<br>CO₂: %{y:.2f} t/person<extra></extra>'\n",
    "))\n",
    "fig_scatter.update_layout(**PLOTLY_LAYOUT,\n",
    "    title=dict(text='GDP per Capita vs Per Capita CO₂ (1990–2024)', font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "    xaxis_title='GDP per Capita (USD)', yaxis_title='CO₂ per Capita (tCO₂/person)')\n",
    "\n",
    "# Justice bar\n",
    "_bar = go.Figure(data=[go.Bar(\n",
    "    x=['Japan','World Average','India'], y=[pc_2023, world_pc_2023, india_pc_2023],\n",
    "    marker=dict(color=[RED,BLUE,GREEN], opacity=0.85),\n",
    "    text=[f'{v:.2f}t' for v in [pc_2023, world_pc_2023, india_pc_2023]],\n",
    "    textposition='outside', textfont=dict(color=TEXT, size=13, family=FONT_HEAD),\n",
    "    hovertemplate='<b>%{x}</b><br>%{y:.2f} tCO₂/person<extra></extra>'\n",
    ")])\n",
    "_bar.update_layout(**PLOTLY_LAYOUT,\n",
    "    title=dict(text='Per Capita CO₂ Comparison (2023)', font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "    yaxis_title='tCO₂/person', showlegend=False, height=320)\n",
    "_bar.update_yaxes(range=[0, max(pc_2023, world_pc_2023, india_pc_2023)*1.3])\n",
    "\n",
    "# Justice bubble\n",
    "_bubble = go.Figure(data=[\n",
    "    go.Scatter(x=[japan[japan['year']==2023]['gdp_per_capita'].values[0]], y=[pc_2023],\n",
    "        mode='markers+text', name='Japan', text=['Japan'], textposition='top center',\n",
    "        textfont=dict(color=TEXT, size=13, family=FONT_HEAD),\n",
    "        marker=dict(size=max(30, int(japan[japan['year']==2023]['population'].values[0]/8_000_000)),\n",
    "                    color=RED, opacity=0.75, line=dict(color='white', width=2)),\n",
    "        hovertemplate='<b>Japan</b><br>GDP: $%{x:,.0f}<br>CO₂: %{y:.2f} t/person<extra></extra>'),\n",
    "    go.Scatter(x=[india[india['year']==2023]['gdp_per_capita'].values[0]], y=[india_pc_2023],\n",
    "        mode='markers+text', name='India', text=['India'], textposition='top center',\n",
    "        textfont=dict(color=TEXT, size=13, family=FONT_HEAD),\n",
    "        marker=dict(size=max(30, int(india[india['year']==2023]['population'].values[0]/8_000_000)),\n",
    "                    color=GREEN, opacity=0.75, line=dict(color='white', width=2)),\n",
    "        hovertemplate='<b>India</b><br>GDP: $%{x:,.0f}<br>CO₂: %{y:.2f} t/person<extra></extra>'),\n",
    "    go.Scatter(x=[world[world['year']==2023]['gdp_per_capita'].values[0]], y=[world_pc_2023],\n",
    "        mode='markers+text', name='World Avg', text=['World Avg'], textposition='top center',\n",
    "        textfont=dict(color=TEXT, size=13, family=FONT_HEAD),\n",
    "        marker=dict(size=40, color=BLUE, opacity=0.75, line=dict(color='white', width=2)),\n",
    "        hovertemplate='<b>World Avg</b><br>GDP: $%{x:,.0f}<br>CO₂: %{y:.2f} t/person<extra></extra>'),\n",
    "])\n",
    "_bubble.update_layout(**PLOTLY_LAYOUT,\n",
    "    title=dict(text='Wealth vs Emissions — Bubble size reflects population (2023)',\n",
    "               font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "    xaxis_title='GDP per Capita (USD)', yaxis_title='Per Capita CO₂ (tCO₂/person)',\n",
    "    height=360, showlegend=True)\n",
    "\n",
    "print(\"✅ All charts built\")\n",
    "\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 6 — Helper UI Components\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def kpi_card(title, value, unit, color=RED, trend=None):\n",
    "    return html.Div([\n",
    "        html.P(title, style={'color':SUBTEXT,'fontSize':'11px','letterSpacing':'1.5px',\n",
    "            'textTransform':'uppercase','margin':'0 0 8px 0','fontFamily':FONT_BODY}),\n",
    "        html.Div([\n",
    "            html.Span(value, style={'color':color,'fontSize':'32px','fontWeight':'700',\n",
    "                'fontFamily':FONT_HEAD,'lineHeight':'1'}),\n",
    "            html.Span(f' {unit}', style={'color':SUBTEXT,'fontSize':'13px',\n",
    "                'marginLeft':'4px','fontFamily':FONT_BODY}),\n",
    "        ]),\n",
    "        html.P(trend or '', style={'color':SUBTEXT,'fontSize':'11px',\n",
    "            'margin':'6px 0 0 0','fontFamily':FONT_BODY}),\n",
    "    ], style={'background':CARD_BG,'border':f'1px solid {BORDER}',\n",
    "        'borderTop':f'2px solid {color}','borderRadius':'8px',\n",
    "        'padding':'20px','flex':'1','minWidth':'180px'})\n",
    "\n",
    "def section_label(text):\n",
    "    return html.P(text, style={'color':SUBTEXT,'fontSize':'10px','letterSpacing':'3px',\n",
    "        'textTransform':'uppercase','fontFamily':FONT_BODY,'marginBottom':'12px',\n",
    "        'borderLeft':f'2px solid {RED}','paddingLeft':'10px'})\n",
    "\n",
    "def section_title(text):\n",
    "    return html.H2(text, style={'color':TEXT,'fontFamily':FONT_HEAD,'fontSize':'28px',\n",
    "        'fontWeight':'400','margin':'0 0 32px 0','letterSpacing':'-0.5px'})\n",
    "\n",
    "def chart_card(fig, gid=None):\n",
    "    kwargs = {'figure': fig, 'config': {'displayModeBar': False}}\n",
    "    if gid:\n",
    "        kwargs['id'] = gid\n",
    "    return html.Div(dcc.Graph(**kwargs),\n",
    "        style={'background':CARD_BG,'borderRadius':'8px','padding':'8px','border':f'1px solid {BORDER}'})\n",
    "\n",
    "print(\"✅ UI helpers defined\")\n",
    "\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 7 — App & Layout\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "app = Dash(__name__, external_stylesheets=[\n",
    "    dbc.themes.BOOTSTRAP,\n",
    "    'https://fonts.googleapis.com/css2?family=Shippori+Mincho:wght@400;700&family=Inter:wght@300;400;500;600&display=swap'\n",
    "])\n",
    "server = app.server\n",
    "app.index_string = '''\n",
    "<!DOCTYPE html>\n",
    "<html>\n",
    "<head>\n",
    "{%metas%}\n",
    "<title>Japan Climate Dashboard</title>\n",
    "{%favicon%}\n",
    "{%css%}\n",
    "<style>\n",
    "    * { box-sizing: border-box; }\n",
    "    html { scroll-behavior: smooth; }\n",
    "    body { background: #F7F7F5; }\n",
    "    ::-webkit-scrollbar { width: 6px; }\n",
    "    ::-webkit-scrollbar-track { background: #F7F7F5; }\n",
    "    ::-webkit-scrollbar-thumb { background: #E0E0DC; border-radius: 3px; }\n",
    "</style>\n",
    "</head>\n",
    "<body>\n",
    "{%app_entry%}\n",
    "<footer>{%config%}{%scripts%}{%renderer%}</footer>\n",
    "</body>\n",
    "</html>\n",
    "'''\n",
    "\n",
    "# ── LANDING ──────────────────────────────────────────────────\n",
    "landing = html.Div(id='landing', style={\n",
    "    'height':'100vh',\n",
    "    'backgroundImage':'url(https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1600&q=80)',\n",
    "    'backgroundSize':'cover','backgroundPosition':'center 40%',\n",
    "    'position':'relative','display':'flex','alignItems':'center',\n",
    "    'justifyContent':'center','flexDirection':'column','textAlign':'center'\n",
    "}, children=[\n",
    "    html.Div(style={'position':'absolute','inset':'0',\n",
    "        'background':'linear-gradient(to bottom, rgba(8,12,20,0.55) 0%, rgba(8,12,20,0.75) 60%, rgba(8,12,20,1) 100%)',\n",
    "        'zIndex':'0'}),\n",
    "    html.Div(style={'position':'relative','zIndex':'1','padding':'0 20px'}, children=[\n",
    "        html.P('TISS Mumbai · BS Analytics & Sustainability Studies', style={\n",
    "            'color':'#86868B','fontSize':'11px','letterSpacing':'3px',\n",
    "            'textTransform':'uppercase','fontFamily':FONT_BODY,'marginBottom':'24px'}),\n",
    "        html.H1(\"JAPAN'S CLIMATE SHIFT\", style={\n",
    "            'color':'#F5F5F7','fontFamily':FONT_HEAD,\n",
    "            'fontSize':'clamp(36px, 7vw, 80px)','fontWeight':'700',\n",
    "            'letterSpacing':'-2px','margin':'0 0 16px 0','lineHeight':'1'}),\n",
    "        html.P('A 35-Year Data Story: 1990 – 2024', style={\n",
    "            'color':'#86868B','fontFamily':FONT_BODY,\n",
    "            'fontSize':'clamp(14px, 2vw, 18px)','fontWeight':'300',\n",
    "            'letterSpacing':'2px','marginBottom':'48px'}),\n",
    "        html.A('Explore the Data →', href='#dashboard', style={\n",
    "            'display':'inline-block','background':'rgba(217,56,30,0.12)',\n",
    "            'color':RED,'border':f'1px solid {RED}','padding':'14px 40px',\n",
    "            'borderRadius':'2px','fontSize':'13px','letterSpacing':'2px',\n",
    "            'textTransform':'uppercase','textDecoration':'none',\n",
    "            'fontFamily':FONT_BODY,'fontWeight':'500'}),\n",
    "    ]),\n",
    "    html.Div('↓', style={'position':'absolute','bottom':'30px',\n",
    "        'color':'#86868B','fontSize':'20px','zIndex':'1'})\n",
    "])\n",
    "\n",
    "# ── MAIN DASHBOARD ────────────────────────────────────────────\n",
    "dashboard = html.Div(id='dashboard', style={\n",
    "    'padding':'80px 5% 60px','maxWidth':'1400px','margin':'0 auto'\n",
    "}, children=[\n",
    "\n",
    "    section_label('Climate Data Analysis · Japan 1990–2024'),\n",
    "    section_title('Carbon Footprint at a Glance'),\n",
    "\n",
    "    # KPI Row\n",
    "    html.Div(style={'display':'flex','gap':'16px','flexWrap':'wrap','marginBottom':'60px'}, children=[\n",
    "        kpi_card('Total CO₂ Emissions',  f'{co2_2023:.1f}',   'MtCO₂',  RED,    '2023 figure'),\n",
    "        kpi_card('Per Capita Emissions', f'{pc_2023:.2f}',    't/person',BLUE,   '2023 figure'),\n",
    "        kpi_card('Change Since 1990',    f'{pct_change}%',    '',        GREEN if pct_change < 0 else RED, 'Per capita change'),\n",
    "        kpi_card('Global CO₂ Share',     f'{share_2023:.2f}', '%',       YELLOW, '2023 share'),\n",
    "    ]),\n",
    "\n",
    "    # Year Slider\n",
    "    html.Div(style={'background':CARD_BG,'border':f'1px solid {BORDER}',\n",
    "        'borderRadius':'8px','padding':'24px 32px','marginBottom':'40px'}, children=[\n",
    "        html.P('FILTER BY YEAR RANGE', style={'color':SUBTEXT,'fontSize':'9px',\n",
    "            'letterSpacing':'3px','fontFamily':FONT_BODY,'marginBottom':'18px'}),\n",
    "        dcc.RangeSlider(\n",
    "            id='year-slider', min=1990, max=2024, step=1, value=[1990, 2024],\n",
    "            marks={y: {'label':str(y),'style':{'color':SUBTEXT,'fontSize':'11px'}}\n",
    "                   for y in range(1990, 2025, 2)},\n",
    "            tooltip={'placement':'bottom','always_visible':False}\n",
    "        )\n",
    "    ]),\n",
    "\n",
    "    # Emissions Trends\n",
    "    html.Div(style={'marginBottom':'60px'}, children=[\n",
    "        section_label('Task B · Emissions Trend Analysis'),\n",
    "        section_title('Two Decades of Carbon'),\n",
    "        html.Div(style={'display':'grid','gridTemplateColumns':'1fr 1fr','gap':'24px'}, children=[\n",
    "            chart_card(fig_total, gid='chart-total'),\n",
    "            chart_card(fig_pc,    gid='chart-pc'),\n",
    "        ])\n",
    "    ]),\n",
    "\n",
    "    # Energy Mix with dropdown\n",
    "    html.Div(style={'marginBottom':'60px'}, children=[\n",
    "        section_label('Task B Extended · Energy Transition'),\n",
    "        section_title('The Energy Story'),\n",
    "        html.Div(style={'background':CARD_BG,'border':f'1px solid {BORDER}',\n",
    "            'borderRadius':'8px','padding':'20px 24px','marginBottom':'16px'}, children=[\n",
    "            html.Div(style={'display':'flex','alignItems':'center','gap':'16px',\n",
    "                'marginBottom':'16px','flexWrap':'wrap'}, children=[\n",
    "                html.P('SELECT SOURCES:', style={'color':SUBTEXT,'fontSize':'9px',\n",
    "                    'letterSpacing':'2px','fontFamily':FONT_BODY,'margin':'0','whiteSpace':'nowrap'}),\n",
    "                dcc.Dropdown(\n",
    "                    id='energy-dropdown',\n",
    "                    options=[\n",
    "                        {'label':'Coal',       'value':'coal'},\n",
    "                        {'label':'Oil',        'value':'oil'},\n",
    "                        {'label':'Gas',        'value':'gas'},\n",
    "                        {'label':'Nuclear',    'value':'nuclear'},\n",
    "                        {'label':'Renewables', 'value':'renewables'},\n",
    "                    ],\n",
    "                    value=['coal','oil','gas','nuclear','renewables'],\n",
    "                    multi=True,\n",
    "                    style={'flex':'1','minWidth':'300px','fontFamily':FONT_BODY,'fontSize':'12px'}\n",
    "                ),\n",
    "            ]),\n",
    "            dcc.Graph(id='chart-energy', config={'displayModeBar':False})\n",
    "        ]),\n",
    "        html.P(\n",
    "            \"Nuclear energy collapsed after the 2011 Fukushima disaster, forcing Japan to surge fossil fuel use. \"\n",
    "            \"Renewables have gradually grown post-2015 under Japan's Feed-in Tariff policy.\",\n",
    "            style={'color':SUBTEXT,'fontSize':'13px','marginTop':'16px',\n",
    "                   'fontFamily':FONT_BODY,'lineHeight':'1.7','maxWidth':'800px'}\n",
    "        )\n",
    "    ]),\n",
    "\n",
    "    # Comparison + Donut\n",
    "    html.Div(style={'marginBottom':'60px'}, children=[\n",
    "        section_label('Task C · Carbon Inequality Analysis'),\n",
    "        section_title('Japan in the World'),\n",
    "        html.Div(style={'display':'grid','gridTemplateColumns':'2fr 1fr','gap':'24px'}, children=[\n",
    "            chart_card(fig_compare),\n",
    "            chart_card(fig_donut),\n",
    "        ])\n",
    "    ]),\n",
    "\n",
    "    # Scatter\n",
    "    html.Div(style={'marginBottom':'60px'}, children=[\n",
    "        section_label('Task D · Wealth vs Emissions'),\n",
    "        section_title('GDP Growth & Carbon Decoupling'),\n",
    "        chart_card(fig_scatter),\n",
    "        html.P(\n",
    "            \"Each point is one year. Rising GDP alongside falling emissions shows Japan's \"\n",
    "            \"economic growth is increasingly decoupled from carbon output.\",\n",
    "            style={'color':SUBTEXT,'fontSize':'13px','marginTop':'16px',\n",
    "                   'fontFamily':FONT_BODY,'lineHeight':'1.7','maxWidth':'800px'}\n",
    "        )\n",
    "    ]),\n",
    "])\n",
    "\n",
    "# ── CLIMATE JUSTICE ───────────────────────────────────────────\n",
    "justice = html.Div(id='climate-justice', style={\n",
    "    'background':'#EFEFEC','borderTop':f'2px solid {BORDER}','padding':'80px 5%',\n",
    "}, children=[\n",
    "    html.Div(style={'maxWidth':'1100px','margin':'0 auto'}, children=[\n",
    "\n",
    "        section_label('Task E · Climate Justice Analysis'),\n",
    "        section_title('Who Bears the Responsibility?'),\n",
    "\n",
    "        # Stat panels\n",
    "        html.Div(style={'display':'grid','gridTemplateColumns':'1fr 1fr 1fr','gap':'2px',\n",
    "            'marginBottom':'40px','border':f'1px solid {BORDER}','borderRadius':'6px','overflow':'hidden'}, children=[\n",
    "            html.Div([\n",
    "                html.P('JAPAN', style={'color':SUBTEXT,'fontSize':'9px','letterSpacing':'3px','fontFamily':FONT_BODY,'margin':'0 0 10px 0'}),\n",
    "                html.P(f'{pc_2023:.1f}t', style={'color':RED,'fontSize':'48px','fontFamily':FONT_HEAD,'fontWeight':'700','margin':'0','lineHeight':'1'}),\n",
    "                html.P('per capita CO₂ (2023)', style={'color':SUBTEXT,'fontSize':'12px','fontFamily':FONT_BODY,'margin':'8px 0 4px 0'}),\n",
    "                html.P(f'{round(pc_2023/world_pc_2023,1)}× the world average', style={'color':RED,'fontSize':'12px','fontWeight':'600','fontFamily':FONT_BODY,'margin':'0'}),\n",
    "            ], style={'background':CARD_BG,'padding':'32px','borderLeft':f'4px solid {RED}'}),\n",
    "\n",
    "            html.Div([\n",
    "                html.P('WORLD AVERAGE', style={'color':SUBTEXT,'fontSize':'9px','letterSpacing':'3px','fontFamily':FONT_BODY,'margin':'0 0 10px 0'}),\n",
    "                html.P(f'{world_pc_2023:.1f}t', style={'color':BLUE,'fontSize':'48px','fontFamily':FONT_HEAD,'fontWeight':'700','margin':'0','lineHeight':'1'}),\n",
    "                html.P('per capita CO₂ (2023)', style={'color':SUBTEXT,'fontSize':'12px','fontFamily':FONT_BODY,'margin':'8px 0 4px 0'}),\n",
    "                html.P('Global benchmark', style={'color':BLUE,'fontSize':'12px','fontWeight':'600','fontFamily':FONT_BODY,'margin':'0'}),\n",
    "            ], style={'background':CARD_BG,'padding':'32px','borderLeft':f'4px solid {BLUE}'}),\n",
    "\n",
    "            html.Div([\n",
    "                html.P('INDIA', style={'color':SUBTEXT,'fontSize':'9px','letterSpacing':'3px','fontFamily':FONT_BODY,'margin':'0 0 10px 0'}),\n",
    "                html.P(f'{india_pc_2023:.1f}t', style={'color':GREEN,'fontSize':'48px','fontFamily':FONT_HEAD,'fontWeight':'700','margin':'0','lineHeight':'1'}),\n",
    "                html.P('per capita CO₂ (2023)', style={'color':SUBTEXT,'fontSize':'12px','fontFamily':FONT_BODY,'margin':'8px 0 4px 0'}),\n",
    "                html.P(f'Japan emits {round(pc_2023/india_pc_2023,1)}× more per person', style={'color':GREEN,'fontSize':'12px','fontWeight':'600','fontFamily':FONT_BODY,'margin':'0'}),\n",
    "            ], style={'background':CARD_BG,'padding':'32px','borderLeft':f'4px solid {GREEN}'}),\n",
    "        ]),\n",
    "\n",
    "        # Bar chart\n",
    "        html.Div(style={'background':CARD_BG,'border':f'1px solid {BORDER}',\n",
    "            'borderRadius':'6px','padding':'8px','marginBottom':'24px'}, children=[\n",
    "            dcc.Graph(figure=_bar, config={'displayModeBar':False})\n",
    "        ]),\n",
    "\n",
    "        # Bubble chart\n",
    "        html.Div(style={'background':CARD_BG,'border':f'1px solid {BORDER}',\n",
    "            'borderRadius':'6px','padding':'8px','marginBottom':'40px'}, children=[\n",
    "            dcc.Graph(figure=_bubble, config={'displayModeBar':False})\n",
    "        ]),\n",
    "\n",
    "        # Sources + footer\n",
    "        html.Div(style={'borderTop':f'1px solid {BORDER}','paddingTop':'28px'}, children=[\n",
    "            html.P('Data Sources', style={'color':TEXT,'fontFamily':FONT_HEAD,'fontSize':'15px','marginBottom':'10px'}),\n",
    "            html.P('Our World in Data — CO₂ and Greenhouse Gas Emissions (2024). ourworldindata.org/co2-emissions',\n",
    "                   style={'color':SUBTEXT,'fontSize':'11px','fontFamily':FONT_BODY,'margin':'3px 0'}),\n",
    "            html.P('Our World in Data — Energy Mix (2024). ourworldindata.org/energy-mix',\n",
    "                   style={'color':SUBTEXT,'fontSize':'11px','fontFamily':FONT_BODY,'margin':'3px 0'}),\n",
    "            html.P('World Bank — GDP per Capita (2024). data.worldbank.org',\n",
    "                   style={'color':SUBTEXT,'fontSize':'11px','fontFamily':FONT_BODY,'margin':'3px 0'}),\n",
    "            html.Div(style={'marginTop':'20px','paddingTop':'20px','borderTop':f'1px solid {BORDER}'}, children=[\n",
    "                html.P('BS in Analytics and Sustainability Studies (2024–28) · TISS Mumbai  ·  Climate Change, Sustainability and Development · Assignment I',\n",
    "                       style={'color':SUBTEXT,'fontSize':'10px','fontFamily':FONT_BODY,'letterSpacing':'0.5px'}),\n",
    "            ])\n",
    "        ])\n",
    "    ])\n",
    "])\n",
    "\n",
    "app.layout = html.Div(\n",
    "    style={'backgroundColor':BG,'fontFamily':FONT_BODY},\n",
    "    children=[landing, dashboard, justice]\n",
    ")\n",
    "\n",
    "print(\"✅ Layout built\")\n",
    "\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 8 — Callbacks\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "@app.callback(\n",
    "    Output('chart-total', 'figure'),\n",
    "    Output('chart-pc',    'figure'),\n",
    "    Input('year-slider',  'value')\n",
    ")\n",
    "def update_trends(year_range):\n",
    "    y0, y1 = year_range\n",
    "    j = japan[(japan['year'] >= y0) & (japan['year'] <= y1)]\n",
    "\n",
    "    f1 = go.Figure()\n",
    "    f1.add_trace(go.Scatter(x=j['year'], y=j['co2_mt'], mode='lines',\n",
    "        line=dict(color=RED, width=3), fill='tozeroy', fillcolor='rgba(217,56,30,0.08)',\n",
    "        hovertemplate='<b>%{x}</b><br>%{y:.1f} MtCO₂<extra></extra>'))\n",
    "    for yr, lbl in [(2011,'Fukushima'),(2016,'Paris Agmt')]:\n",
    "        if y0 <= yr <= y1:\n",
    "            f1.add_vline(x=yr, line_dash='dash', line_color=SUBTEXT, line_width=1, opacity=0.5)\n",
    "            f1.add_annotation(x=yr, y=j['co2_mt'].max(), text=lbl, showarrow=False,\n",
    "                font=dict(color=SUBTEXT, size=10, family=FONT_BODY), xshift=5, yshift=10)\n",
    "    f1.update_layout(**PLOTLY_LAYOUT,\n",
    "        title=dict(text='Total CO₂ Emissions (MtCO₂)', font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "        yaxis_title='MtCO₂')\n",
    "\n",
    "    f2 = go.Figure()\n",
    "    f2.add_trace(go.Scatter(x=j['year'], y=j['co2_per_capita'], mode='lines',\n",
    "        line=dict(color=BLUE, width=3), fill='tozeroy', fillcolor='rgba(31,69,110,0.08)',\n",
    "        hovertemplate='<b>%{x}</b><br>%{y:.2f} tCO₂/person<extra></extra>'))\n",
    "    for yr, lbl in [(2011,'Fukushima'),(2016,'Paris Agmt')]:\n",
    "        if y0 <= yr <= y1:\n",
    "            f2.add_vline(x=yr, line_dash='dash', line_color=SUBTEXT, line_width=1, opacity=0.5)\n",
    "            f2.add_annotation(x=yr, y=j['co2_per_capita'].max(), text=lbl, showarrow=False,\n",
    "                font=dict(color=SUBTEXT, size=10, family=FONT_BODY), xshift=5, yshift=10)\n",
    "    f2.update_layout(**PLOTLY_LAYOUT,\n",
    "        title=dict(text='Per Capita CO₂ Emissions (tCO₂/person)', font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "        yaxis_title='tCO₂/person')\n",
    "\n",
    "    return f1, f2\n",
    "\n",
    "\n",
    "@app.callback(\n",
    "    Output('chart-energy', 'figure'),\n",
    "    Input('energy-dropdown', 'value'),\n",
    "    Input('year-slider',     'value')\n",
    ")\n",
    "def update_energy(selected, year_range):\n",
    "    y0, y1 = year_range\n",
    "    j = japan[(japan['year'] >= y0) & (japan['year'] <= y1)]\n",
    "    fig = go.Figure()\n",
    "    if selected:\n",
    "        for src in selected:\n",
    "            lc, fc = ENERGY_COLORS[src]\n",
    "            fig.add_trace(go.Scatter(\n",
    "                x=j['year'], y=j[src], mode='lines', name=ENERGY_LABELS[src],\n",
    "                stackgroup='one', line=dict(width=0.5, color=lc), fillcolor=fc,\n",
    "                hovertemplate=f'<b>{ENERGY_LABELS[src]}</b><br>%{{y:.0f}} TWh<extra></extra>'\n",
    "            ))\n",
    "    if y0 <= 2011 <= y1:\n",
    "        fig.add_vline(x=2011, line_dash='dash', line_color=SUBTEXT, line_width=1, opacity=0.6)\n",
    "        fig.add_annotation(x=2011, y=6500, text='Fukushima — Nuclear collapse',\n",
    "            showarrow=False, font=dict(color=SUBTEXT, size=10, family=FONT_BODY), xshift=8)\n",
    "    fig.update_layout(**PLOTLY_LAYOUT,\n",
    "        title=dict(text='Energy Mix by Source (TWh)', font=dict(color=TEXT, size=14, family=FONT_HEAD)),\n",
    "        yaxis_title='TWh')\n",
    "    return fig\n",
    "\n",
    "print(\"✅ Callbacks registered\")\n",
    "\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 9 — Run\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "import webbrowser\n",
    "from threading import Timer\n",
    "\n",
    "def open_browser():\n",
    "    webbrowser.open_new(\"http://127.0.0.1:8050\")\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    Timer(1.5, open_browser).start()\n",
    "    app.run(debug=False, port=8050)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c931e2b7-f288-4844-911c-37ffbd34ad0f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
